id: I96DD5A85
ocr_import_info:
  timestamp: '2023-06-28T16:17:44.984862+00:00'
  batch_id: batch-2faa
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 19:40:03.350789+00:00
last_modified: 2023-06-28 19:40:03.350796+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM40
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM40
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སློབ་གཉེར་བྱེད་ཚུལ་གྱི་བསླབ་བྱ་ལེ་ཚན་གཉིས་སོགས།
  languages:
  - bo
  author: ལྕང་ལུང་པཎྜི་ཏ་ངག་དབང་བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9249881810514895
  ocr_word_median_confidence_index: 0.9901051
bases:
  I1NLM40_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM40_001
      total_pages: 260
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM40_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9901051
      ocr_word_mean_confidence_index: 0.9249881810514895
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
